import './globals.css'
import { Inter } from 'next/font/google'
import {LichessProvider, OAuthProvider} from "@/app/context";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <OAuthProvider>
      <LichessProvider>
        {children}
      </LichessProvider>
      </OAuthProvider>
      </body>
    </html>
  )
}
