import './globals.css'
import { Inter } from 'next/font/google'
import {LichessProvider, OAuthProvider} from "@/app/context";

const inter = Inter({ subsets: ['latin'] })

import './globals.css'

export const metadata = {
  title: 'chess client app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
      <OAuthProvider>
      <LichessProvider>
          <div className='h-full'>
              {children}
          </div>
      </LichessProvider>
      </OAuthProvider>
      </body>
    </html>
  )
}
